version: "3"

services:
    nginx:
      image: nginx:1.13-alpine
      container_name: ben-web
      ports:
        - "8082:80"
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
    backend:
      build: .
      container_name: ben_site